spring:
  application:
    name: obsidianToGpt
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:4033/filemanager
    driverClassName: org.postgresql.Driver
    username: ${ObToGP_DB_USERNAME}
    password: ${ObToGP_DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://otg.herrscote.de/oauth
