spring:
  application:
    name: obsidianToGpt
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/obsidian_db
      driverClassName: org.postgresql.Driver
      username: ${ObToGP_DB_USERNAME}
      password: ${ObToGP_DB_PASSWORD}
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
